### ISSUE TITLE
Install requirements

### ISSUE THREAD

**Issue by merrx** [paulscherrerinstitute/py_elog#19]
On the first page it is stated elog only depends on `passlib` and `requests`, but nowadays it also depends on `lxml`.
I am not sure, why the `install_requires` section in setup.py is commented out, but I believe the conda way of install is the preferred one and doesn't use setup.py

I also like to make an addition: The pip way of install via
`pip3 install https://github.com/paulscherrerinstitute/py_elog/archive/master.zip`
This way you don't have to install the large conda package. But as the master branch could be in an arbitrary working state, this isn't the perfect solution. Normally it should be something like `https://github.com/paulscherrerinstitute/py_elog/releases/latest/download/asset-name.zip`, but I could not figure out the correct link. As this repository normally doesn't show much activity, the master.zip link should be fine. One note: right now you have to install the dependencies by yourself. 

It would be great, if the release also gets pushed to pypi to make this an official way to install the package.
But I'm not sure, if there are name conflicts or this is not intended.

**Comment by simongregorebner** [comment]
The uncommenting of the `install_requires` section was probably due to some issues together with the conda packaging. This should be fixed now with f911c0f7b57933151793f7510b7cce5b165cf503

**Comment by simongregorebner** [comment]
you can now do a `pip install https://github.com/paulscherrerinstitute/py_elog/archive/refs/heads/master.zip` or with any further release `https://github.com/paulscherrerinstitute/py_elog/archive/refs/tags/1.3.12.zip` (this release doesn't exist yet)

regarding pushing to pypi I need to check - to what I can remember it was pretty complicated to get things pushing to there

hope this solves this issue - otherwise please reopen
